# Generated by Django 5.2.6 on 2025-10-12 01:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movies', '0002_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('zoom_level', models.IntegerField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name='MoviePopularity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_count', models.IntegerField(default=0)),
                ('view_count', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movie')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='popularity.region')),
            ],
            options={
                'unique_together': {('movie', 'region')},
            },
        ),
    ]
